version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    depends_on:
            - rabbitmq
  nservicebusservice:
    image: ${DOCKER_REGISTRY-}nservicebusservice
    build:
      context: .
      dockerfile: NServiceBusService/Dockerfile
    depends_on:
            - rabbitmq
  rabbitmq:
        image: "rabbitmq:3.8-management"
        ports:
            - "15672:15672"
        healthcheck:
            test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
            interval: 10s
            retries: 5
